### ISSUE TITLE
Compile problem and some include problems

### ISSUE THREAD

**Issue by ganler** [csukuangfj/OpenCNN#1]
## Compile problem:
- sys: Ubuntu 16.04
- compiler: g++7.4

And I fixed this by modifying the cmakelist:
```cmake
if(UNIX AND NOT APPLE)
    target_link_libraries(
        core
        -pthread
        -lprotobuf # What I added.
        )
endif()
```

## include problems
You should `#include <functional>` in your `network.hpp`, or another compile error with gcc.

Das is alles. Danke.(Ich kann nur ein bisschen Deutsch sprechen.)

**Comment by ganler** [comment]
BTW. You'd better tell the users to install gtest(It seems that you've ignored this in your dependency list.).

**Comment by csukuangfj** [comment]
@ganler 

1. Could you please show the cmake log for this line: https://github.com/csukuangfj/OpenCNN/blob/642ba071be560390ebf643cab2a1224853e87cd7/cmake/protobuf.cmake#L10

It should find your protobuf library automatically and link it without your intervention.

2. Gtest is included in the project (https://github.com/csukuangfj/OpenCNN/tree/master/test/gtest) and it is compiled from source. No separate installation is required.

3. I am considering to replace the cmake build system with Bazel.

---

Super! Sie können viel Deutsch schreiben 👍

**Comment by ganler** [comment]
@csukuangfj 
1. It seems that my cmake didn't find protobuf:
Here is the messages:
```bash
➜  CXXTEST cd build
➜  build cmake ..
-- protobuf libs: 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ganler/Desktop/GanlerCodes/CXXTEST/build
➜  build 
```
2. I ignored there's already a gtest in your project.(This is my first time to use the tools of google, sorry.)

**Comment by ganler** [comment]
Ich bin ein Student(Informatik) von der Tongji Uni(China). Es gibt viele Deutsche Studenten in unserer Uni.
